# Generated by Django 4.0.6 on 2023-03-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Grocery', 'Grocery'), ('Cold Drinks', 'Cold Drinks'), (
                    'Oil', 'Oil'), ('Soap', 'Soap'), ('Others', 'Others')], max_length=60, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
